branch-defaults:
  default:
    environment: huy-project-2-dev
    group_suffix: null
global:
  application_name: huy-project-2
  branch: null
  default_ec2_keyname: vockey
  default_platform: Node.js 18 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
